// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using LFMova.Infrastructure.Data;

#nullable disable

namespace LFMova.Infrastructure.Migrations
{
    [DbContext(typeof(LFMovaDbContext))]
    [Migration("20260922182310_HoraLlegadaConductorEnServicioPasajero")]
    partial class HoraLlegadaConductorEnServicioPasajero
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LFMova.Domain.Entities.Conductor", b =>
                {
                    b.Property<int>("ConductorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConductorId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("ConductorId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Conductores");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.Conversacion", b =>
                {
                    b.Property<int>("ConversacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConversacionId"));

                    b.Property<int>("ServicioPasajeroId")
                        .HasColumnType("integer");

                    b.HasKey("ConversacionId");

                    b.HasIndex("ServicioPasajeroId")
                        .IsUnique();

                    b.ToTable("Conversaciones");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.Empleado", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmpleadoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Barrio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("EmpleadoId");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.Empresa", b =>
                {
                    b.Property<int>("EmpresaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmpresaId"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("Cif")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EmpresaId");

                    b.HasIndex("Cif")
                        .IsUnique();

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.Evidencia", b =>
                {
                    b.Property<int>("EvidenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EvidenciaId"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IncidenciaId")
                        .HasColumnType("integer");

                    b.Property<string>("ReferenciaArchivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("EvidenciaId");

                    b.HasIndex("IncidenciaId");

                    b.ToTable("Evidencias");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.ImportacionExcel", b =>
                {
                    b.Property<int>("ImportacionExcelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ImportacionExcelId"));

                    b.Property<int>("CoordinadorId")
                        .HasColumnType("integer");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaImportacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ImportacionExcelId");

                    b.HasIndex("CoordinadorId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("ImportacionesExcel");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.Incidencia", b =>
                {
                    b.Property<int>("IncidenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IncidenciaId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Latitud")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitud")
                        .HasColumnType("double precision");

                    b.Property<int>("ServicioPasajeroId")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("IncidenciaId");

                    b.HasIndex("ServicioPasajeroId");

                    b.ToTable("Incidencias");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.Jornada", b =>
                {
                    b.Property<int>("JornadaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("JornadaId"));

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("FechaOperativa")
                        .HasColumnType("date");

                    b.HasKey("JornadaId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Jornadas");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.Mensaje", b =>
                {
                    b.Property<int>("MensajeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MensajeId"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ConversacionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("MensajeId");

                    b.HasIndex("ConversacionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Mensajes");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.Notificacion", b =>
                {
                    b.Property<int>("NotificacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificacionId"));

                    b.Property<string>("Enlace")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Leida")
                        .HasColumnType("boolean");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("NotificacionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.ProgramacionTransporte", b =>
                {
                    b.Property<int>("ProgramacionTransporteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProgramacionTransporteId"));

                    b.Property<string>("BarrioRecogida")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DireccionRecogida")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("Hora")
                        .HasColumnType("time without time zone");

                    b.Property<int>("SedeId")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("ProgramacionTransporteId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("Fecha");

                    b.HasIndex("SedeId");

                    b.ToTable("ProgramacionesTransporte");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.Sede", b =>
                {
                    b.Property<int>("SedeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SedeId"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("Barrio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<double?>("Latitud")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitud")
                        .HasColumnType("double precision");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SedeId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Sedes");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.Servicio", b =>
                {
                    b.Property<int>("ServicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServicioId"));

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime?>("HoraFinReal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("HoraInicioReal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeOnly>("HoraProgramada")
                        .HasColumnType("time without time zone");

                    b.Property<int>("JornadaId")
                        .HasColumnType("integer");

                    b.Property<int>("SedeId")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<int?>("UnidadOperativaId")
                        .HasColumnType("integer");

                    b.HasKey("ServicioId");

                    b.HasIndex("Estado");

                    b.HasIndex("Fecha");

                    b.HasIndex("JornadaId");

                    b.HasIndex("SedeId");

                    b.HasIndex("UnidadOperativaId");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.ServicioPasajero", b =>
                {
                    b.Property<int>("ServicioPasajeroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServicioPasajeroId"));

                    b.Property<string>("DireccionRecogida")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("HoraLlegadaConductor")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Latitud")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitud")
                        .HasColumnType("double precision");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<int>("ProgramacionTransporteId")
                        .HasColumnType("integer");

                    b.Property<int>("ServicioId")
                        .HasColumnType("integer");

                    b.HasKey("ServicioPasajeroId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("ProgramacionTransporteId")
                        .IsUnique();

                    b.HasIndex("ServicioId");

                    b.ToTable("ServiciosPasajero");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.TokenVerificacion", b =>
                {
                    b.Property<int>("TokenVerificacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TokenVerificacionId"));

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<bool>("Utilizado")
                        .HasColumnType("boolean");

                    b.HasKey("TokenVerificacionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TokensVerificacion");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.UbicacionRecogidaHistorica", b =>
                {
                    b.Property<int>("UbicacionRecogidaHistoricaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UbicacionRecogidaHistoricaId"));

                    b.Property<string>("Barrio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Latitud")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitud")
                        .HasColumnType("double precision");

                    b.HasKey("UbicacionRecogidaHistoricaId");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("UbicacionesRecogidaHistorica");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.UnidadOperativa", b =>
                {
                    b.Property<int>("UnidadOperativaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UnidadOperativaId"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<int>("ConductorId")
                        .HasColumnType("integer");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("integer");

                    b.HasKey("UnidadOperativaId");

                    b.HasIndex("ConductorId");

                    b.HasIndex("VehiculoId")
                        .IsUnique();

                    b.ToTable("UnidadesOperativas");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("CorreoConfirmado")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.UsuarioRol", b =>
                {
                    b.Property<int>("UsuarioRolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuarioRolId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("UsuarioRolId");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioRoles");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.Vehiculo", b =>
                {
                    b.Property<int>("VehiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VehiculoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer");

                    b.Property<int>("ConductorId")
                        .HasColumnType("integer");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("VigenciaSoat")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("VigenciaTecnomecanica")
                        .HasColumnType("date");

                    b.HasKey("VehiculoId");

                    b.HasIndex("ConductorId");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.VinculacionConductorEmpresa", b =>
                {
                    b.Property<int>("VinculacionConductorEmpresaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VinculacionConductorEmpresaId"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<int>("ConductorId")
                        .HasColumnType("integer");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.HasKey("VinculacionConductorEmpresaId");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("ConductorId", "EmpresaId")
                        .IsUnique();

                    b.ToTable("VinculacionesConductorEmpresa");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.Conductor", b =>
                {
                    b.HasOne("LFMova.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Conductor")
                        .HasForeignKey("LFMova.Domain.Entities.Conductor", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.Conversacion", b =>
                {
                    b.HasOne("LFMova.Domain.Entities.ServicioPasajero", "ServicioPasajero")
                        .WithOne("Conversacion")
                        .HasForeignKey("LFMova.Domain.Entities.Conversacion", "ServicioPasajeroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServicioPasajero");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.Empleado", b =>
                {
                    b.HasOne("LFMova.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Empleados")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LFMova.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Empleado")
                        .HasForeignKey("LFMova.Domain.Entities.Empleado", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.Evidencia", b =>
                {
                    b.HasOne("LFMova.Domain.Entities.Incidencia", "Incidencia")
                        .WithMany("Evidencias")
                        .HasForeignKey("IncidenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Incidencia");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.ImportacionExcel", b =>
                {
                    b.HasOne("LFMova.Domain.Entities.Usuario", "Coordinador")
                        .WithMany()
                        .HasForeignKey("CoordinadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LFMova.Domain.Entities.Empresa", "Empresa")
                        .WithMany("ImportacionesExcel")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coordinador");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.Incidencia", b =>
                {
                    b.HasOne("LFMova.Domain.Entities.ServicioPasajero", "ServicioPasajero")
                        .WithMany("Incidencias")
                        .HasForeignKey("ServicioPasajeroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServicioPasajero");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.Jornada", b =>
                {
                    b.HasOne("LFMova.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Jornadas")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.Mensaje", b =>
                {
                    b.HasOne("LFMova.Domain.Entities.Conversacion", "Conversacion")
                        .WithMany("Mensajes")
                        .HasForeignKey("ConversacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LFMova.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Mensajes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.Notificacion", b =>
                {
                    b.HasOne("LFMova.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Notificaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.ProgramacionTransporte", b =>
                {
                    b.HasOne("LFMova.Domain.Entities.Empleado", "Empleado")
                        .WithMany("ProgramacionesTransporte")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LFMova.Domain.Entities.Empresa", "Empresa")
                        .WithMany("ProgramacionesTransporte")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LFMova.Domain.Entities.Sede", "Sede")
                        .WithMany("ProgramacionesTransporte")
                        .HasForeignKey("SedeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Empresa");

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.Sede", b =>
                {
                    b.HasOne("LFMova.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Sedes")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.Servicio", b =>
                {
                    b.HasOne("LFMova.Domain.Entities.Jornada", "Jornada")
                        .WithMany("Servicios")
                        .HasForeignKey("JornadaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LFMova.Domain.Entities.Sede", "Sede")
                        .WithMany("Servicios")
                        .HasForeignKey("SedeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LFMova.Domain.Entities.UnidadOperativa", "UnidadOperativa")
                        .WithMany("Servicios")
                        .HasForeignKey("UnidadOperativaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Jornada");

                    b.Navigation("Sede");

                    b.Navigation("UnidadOperativa");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.ServicioPasajero", b =>
                {
                    b.HasOne("LFMova.Domain.Entities.Empleado", "Empleado")
                        .WithMany("ServiciosPasajero")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LFMova.Domain.Entities.ProgramacionTransporte", "ProgramacionTransporte")
                        .WithOne("ServicioPasajero")
                        .HasForeignKey("LFMova.Domain.Entities.ServicioPasajero", "ProgramacionTransporteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LFMova.Domain.Entities.Servicio", "Servicio")
                        .WithMany("ServiciosPasajero")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("ProgramacionTransporte");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.TokenVerificacion", b =>
                {
                    b.HasOne("LFMova.Domain.Entities.Usuario", "Usuario")
                        .WithMany("TokensVerificacion")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.UbicacionRecogidaHistorica", b =>
                {
                    b.HasOne("LFMova.Domain.Entities.Empleado", "Empleado")
                        .WithMany("UbicacionesRecogidaHistorica")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.UnidadOperativa", b =>
                {
                    b.HasOne("LFMova.Domain.Entities.Conductor", "Conductor")
                        .WithMany("UnidadesOperativas")
                        .HasForeignKey("ConductorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LFMova.Domain.Entities.Vehiculo", "Vehiculo")
                        .WithOne("UnidadOperativa")
                        .HasForeignKey("LFMova.Domain.Entities.UnidadOperativa", "VehiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conductor");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.UsuarioRol", b =>
                {
                    b.HasOne("LFMova.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LFMova.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.Vehiculo", b =>
                {
                    b.HasOne("LFMova.Domain.Entities.Conductor", "Conductor")
                        .WithMany("Vehiculos")
                        .HasForeignKey("ConductorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conductor");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.VinculacionConductorEmpresa", b =>
                {
                    b.HasOne("LFMova.Domain.Entities.Conductor", "Conductor")
                        .WithMany("VinculacionesConductorEmpresa")
                        .HasForeignKey("ConductorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LFMova.Domain.Entities.Empresa", "Empresa")
                        .WithMany("VinculacionesConductorEmpresa")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conductor");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.Conductor", b =>
                {
                    b.Navigation("UnidadesOperativas");

                    b.Navigation("Vehiculos");

                    b.Navigation("VinculacionesConductorEmpresa");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.Conversacion", b =>
                {
                    b.Navigation("Mensajes");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.Empleado", b =>
                {
                    b.Navigation("ProgramacionesTransporte");

                    b.Navigation("ServiciosPasajero");

                    b.Navigation("UbicacionesRecogidaHistorica");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.Empresa", b =>
                {
                    b.Navigation("Empleados");

                    b.Navigation("ImportacionesExcel");

                    b.Navigation("Jornadas");

                    b.Navigation("ProgramacionesTransporte");

                    b.Navigation("Sedes");

                    b.Navigation("VinculacionesConductorEmpresa");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.Incidencia", b =>
                {
                    b.Navigation("Evidencias");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.Jornada", b =>
                {
                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.ProgramacionTransporte", b =>
                {
                    b.Navigation("ServicioPasajero");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.Sede", b =>
                {
                    b.Navigation("ProgramacionesTransporte");

                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.Servicio", b =>
                {
                    b.Navigation("ServiciosPasajero");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.ServicioPasajero", b =>
                {
                    b.Navigation("Conversacion");

                    b.Navigation("Incidencias");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.UnidadOperativa", b =>
                {
                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Conductor");

                    b.Navigation("Empleado");

                    b.Navigation("Mensajes");

                    b.Navigation("Notificaciones");

                    b.Navigation("TokensVerificacion");

                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("LFMova.Domain.Entities.Vehiculo", b =>
                {
                    b.Navigation("UnidadOperativa");
                });
#pragma warning restore 612, 618
        }
    }
}
